http://shiny.leg.ufpr.br/clobos/analise_descritiva/
http://shiny.leg.ufpr.br/clobos/Comparacion_normal_t/
http://shiny.leg.ufpr.br/clobos/diseno_experimentos/
http://shiny.leg.ufpr.br/clobos/distribuicao_normal/
http://shiny.leg.ufpr.br/clobos/distribuicao_t_Normal/
http://shiny.leg.ufpr.br/clobos/Escojiendo_base_datos/
http://shiny.leg.ufpr.br/clobos/histograma_vac/
http://shiny.leg.ufpr.br/clobos/Normal/
http://shiny.leg.ufpr.br/clobos/normal_media_diferente/
http://shiny.leg.ufpr.br/clobos/normal_varianza_diferente/
http://shiny.leg.ufpr.br/clobos/probabilidades/
http://shiny.leg.ufpr.br/clobos/simetria_y_asimetria/
http://shiny.leg.ufpr.br/clobos/Bernoulli/
http://shiny.leg.ufpr.br/clobos/Exponencial/
http://shiny.leg.ufpr.br/clobos/modelos_lineales/
